plugins {
    id 'maven-publish'
}

apply from: rootProject.file('gradle/release-versions.gradle')
apply from: rootProject.file('gradle/version-utils.gradle')
apply from: rootProject.file('gradle/project-versioning.gradle')

apply plugin: isUnmappedMinecraftTarget
        ? 'net.fabricmc.fabric-loom'
        : 'net.fabricmc.fabric-loom-remap'

apply from: rootProject.file('gradle/loom.gradle')
apply from: rootProject.file('gradle/dependencies.gradle')
apply from: rootProject.file('gradle/resources.gradle')
apply from: rootProject.file('gradle/java-artifacts.gradle')
apply from: rootProject.file('gradle/publishing.gradle')
