# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.warning.mode=summary

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false
dev.kikugie.stonecutter.hard_mode=true
dev.kikugie.stonecutter.generate_switch_actions=false

# Shared Fabric Properties
loader_version=0.19.2

# Mod Properties
mod_name=Fresh Armor Bar
mod_author=ZeroXXII
mod_license=MIT
maven_group=com.fresharmorbar
archives_base_name=FreshArmorBar
