pluginManagement {
	repositories {
		mavenLocal()
		mavenCentral()
		gradlePluginPortal()
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'KikuGie Snapshots'
			url = 'https://maven.kikugie.dev/snapshots'
		}
	}
}

plugins {
	id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
	id 'dev.kikugie.stonecutter' version '0.9.4'
}

apply from: 'gradle/release-versions.gradle'
apply from: 'gradle/version-utils.gradle'

List<String> stonecutterMinecraftVersions = ext.stonecutterMinecraftVersions as List<String>

stonecutter.create(getRootProject()) {
	versions(*(stonecutterMinecraftVersions as String[]))
	vcsVersion = '1.20.1'
}

rootProject.name = 'Fresh_Armor_Bar'

apply from: 'gradle/root-tasks.gradle'
apply from: 'gradle/release-validation.gradle'
